#!/usr/bin/env node
/**
 * Build `web/public/llms-full.txt` — the package README plus every agent-skill
 * reference, concatenated into one file an LLM can ingest in a single fetch.
 *
 * Wired as the demo site's `prebuild`, so `vite build` always ships a current
 * copy. Also runnable on its own: `node web/scripts/build-llms.mjs`.
 *
 * `llms.txt` itself (the short index) is hand-maintained at the repo root and
 * mirrored into `web/public/`; this script only produces the FULL bundle.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "../..");
const OUT = path.join(REPO, "web/public/llms-full.txt");

const SKILL_REFS = path.join(REPO, "skills/brookmd/references");

/** Ordered: the narrative docs first, then the skill, then its references. */
const SOURCES = [
  "packages/brookmd/README.md",
  "skills/brookmd/SKILL.md",
  ...readdirSync(SKILL_REFS)
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => path.join("skills/brookmd/references", f)),
];

const HEADER = `# brookmd — full documentation bundle

Generated by web/scripts/build-llms.mjs. Do not edit by hand.
Short index: https://md.hsingh.app/llms.txt
`;

const parts = [HEADER];
for (const rel of SOURCES) {
  const abs = path.join(REPO, rel);
  const body = readFileSync(abs, "utf8").replace(/\s+$/, "");
  parts.push(`\n\n${"=".repeat(78)}\n# Source: ${rel}\n${"=".repeat(78)}\n\n${body}\n`);
}

mkdirSync(path.dirname(OUT), { recursive: true });
const text = parts.join("");
writeFileSync(OUT, text, "utf8");

console.log(
  `llms-full.txt: ${SOURCES.length} sources, ${text.length.toLocaleString("en-US")} chars -> ${path.relative(REPO, OUT)}`,
);
