// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(brook_md_ffiFFI)
import brook_md_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_brook_md_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_brook_md_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBrookMdFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A single streaming-parse session: an [`Arc`]-shared, interior-mutable wrapper
 * over one [`StreamParser`]. uniffi objects are shared by `Arc` and their
 * methods take `&self`, so the parser lives behind a `Mutex` (which also
 * provides the `Sync` half, since [`SendParser`] is `Send`).
 *
 * Feed input with [`append`](Self::append) (returns a `Patch` JSON string),
 * end the stream with [`finalize`](Self::finalize), read the whole document
 * with [`all_blocks`](Self::all_blocks), and start a fresh stream with
 * [`reset`](Self::reset). One `BrookSession` corresponds to one JS-worker stream
 * (one `BrookParser` instance): ids are stable and monotonic for its lifetime
 * and restart at 0 after a `reset`.
 */
public protocol BrookSessionProtocol: AnyObject, Sendable {
    
    /**
     * The whole parsed document (committed + active) in order, as a JSON string
     * of a `Block[]` — the bytes of the WASM `BrookParser.allBlocks` boundary
     * (WIRE.md §1). The one-shot / SSR primitive: `append` the full source,
     * `finalize`, then read this.
     */
    func allBlocks()  -> String
    
    /**
     * Feed the next chunk of markdown. Returns a `Patch` as a JSON string
     * (`{"newly_committed":[…],"active":[…]}`) — the exact bytes of the WASM
     * `BrookParser.append` boundary (WIRE.md §2). Parse it once with any JSON
     * decoder.
     */
    func append(chunk: String)  -> String
    
    /**
     * Length in bytes of the retained source buffer (line endings normalized to
     * `\n`); block `start`/`end` offsets index into it.
     */
    func bufferLen()  -> UInt64
    
    /**
     * End the stream: emit any still-open blocks as committed. Returns a final
     * `Patch` JSON string (WIRE.md §2). After this, `append` is a no-op that
     * returns an empty patch, matching the core parser.
     */
    func finalize()  -> String
    
    /**
     * Discard all parse state and start a fresh stream, preserving this
     * session's configuration. Mirrors the JS worker's `reset` (free the parser
     * and recreate it lazily with the same config): block ids restart from 0.
     */
    func reset() 
    
    /**
     * Total bytes the parser is retaining (source buffer + all rendered HTML for
     * committed and active blocks). For comparing per-session memory cost.
     */
    func retainedBytes()  -> UInt64
    
}
/**
 * A single streaming-parse session: an [`Arc`]-shared, interior-mutable wrapper
 * over one [`StreamParser`]. uniffi objects are shared by `Arc` and their
 * methods take `&self`, so the parser lives behind a `Mutex` (which also
 * provides the `Sync` half, since [`SendParser`] is `Send`).
 *
 * Feed input with [`append`](Self::append) (returns a `Patch` JSON string),
 * end the stream with [`finalize`](Self::finalize), read the whole document
 * with [`all_blocks`](Self::all_blocks), and start a fresh stream with
 * [`reset`](Self::reset). One `BrookSession` corresponds to one JS-worker stream
 * (one `BrookParser` instance): ids are stable and monotonic for its lifetime
 * and restart at 0 after a `reset`.
 */
open class BrookSession: BrookSessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_brook_md_ffi_fn_clone_brooksession(self.handle, $0) }
    }
    /**
     * Bare constructor — equivalent to `new BrookParser()` on the WASM boundary
     * (`StreamParser::new()`, all features at their library defaults: autolinks
     * and alerts **off**, raw HTML escaped, block data off).
     */
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_brook_md_ffi_fn_constructor_brooksession_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_brook_md_ffi_fn_free_brooksession(handle, $0) }
    }

    
    /**
     * Configured constructor — applies `config` through the same setters the JS
     * worker's `makeParser` uses (see [`BrookConfig`]).
     */
public static func newWithConfig(config: BrookConfig) -> BrookSession  {
    return try!  FfiConverterTypeBrookSession_lift(try! rustCall() {
    uniffi_brook_md_ffi_fn_constructor_brooksession_new_with_config(
        FfiConverterTypeBrookConfig_lower(config),$0
    )
})
}
    

    
    /**
     * The whole parsed document (committed + active) in order, as a JSON string
     * of a `Block[]` — the bytes of the WASM `BrookParser.allBlocks` boundary
     * (WIRE.md §1). The one-shot / SSR primitive: `append` the full source,
     * `finalize`, then read this.
     */
open func allBlocks() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_brook_md_ffi_fn_method_brooksession_all_blocks(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Feed the next chunk of markdown. Returns a `Patch` as a JSON string
     * (`{"newly_committed":[…],"active":[…]}`) — the exact bytes of the WASM
     * `BrookParser.append` boundary (WIRE.md §2). Parse it once with any JSON
     * decoder.
     */
open func append(chunk: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_brook_md_ffi_fn_method_brooksession_append(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(chunk),$0
    )
})
}
    
    /**
     * Length in bytes of the retained source buffer (line endings normalized to
     * `\n`); block `start`/`end` offsets index into it.
     */
open func bufferLen() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_brook_md_ffi_fn_method_brooksession_buffer_len(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * End the stream: emit any still-open blocks as committed. Returns a final
     * `Patch` JSON string (WIRE.md §2). After this, `append` is a no-op that
     * returns an empty patch, matching the core parser.
     */
open func finalize() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_brook_md_ffi_fn_method_brooksession_finalize(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Discard all parse state and start a fresh stream, preserving this
     * session's configuration. Mirrors the JS worker's `reset` (free the parser
     * and recreate it lazily with the same config): block ids restart from 0.
     */
open func reset()  {try! rustCall() {
    uniffi_brook_md_ffi_fn_method_brooksession_reset(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Total bytes the parser is retaining (source buffer + all rendered HTML for
     * committed and active blocks). For comparing per-session memory cost.
     */
open func retainedBytes() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_brook_md_ffi_fn_method_brooksession_retained_bytes(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBrookSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = BrookSession

    public static func lift(_ handle: UInt64) throws -> BrookSession {
        return BrookSession(unsafeFromHandle: handle)
    }

    public static func lower(_ value: BrookSession) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BrookSession {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: BrookSession, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrookSession_lift(_ handle: UInt64) throws -> BrookSession {
    return try FfiConverterTypeBrookSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrookSession_lower(_ value: BrookSession) -> UInt64 {
    return FfiConverterTypeBrookSession.lower(value)
}




/**
 * Per-stream parser configuration, mirroring `ParserConfig` in
 * `packages/brookmd/src/types-core.ts` and the setters the JS worker's
 * `makeParser` applies (`packages/brookmd/src/worker.ts`).
 *
 * The record's field defaults reproduce the worker's `?? default` behavior
 * exactly: GFM autolinks and alerts default **on** (LLM output is full of bare
 * URLs and `> [!NOTE]` callouts), everything else off. The five tag/allowlist/
 * scheme fields are optional arrays (`Option<Vec<String>>`), matching the `?:`
 * optional arrays on the TypeScript side — `None` (omitted) is the "feature off"
 * state.
 *
 * Setting `html_allowlist` **or** `drop_html_tags` (even to an empty array)
 * engages the safe raw-HTML sanitizer, exactly as the worker derives its
 * `setHtmlSanitize` on-flag from `htmlAllowlist !== undefined || dropHtmlTags
 * !== undefined`.
 */
public struct BrookConfig: Equatable, Hashable {
    /**
     * GFM extended autolinks (bare `www.`/`http(s)://`/`ftp://` + emails).
     */
    public var gfmAutolinks: Bool
    /**
     * GitHub alerts (`> [!NOTE]` → styled callouts).
     */
    public var gfmAlerts: Bool
    /**
     * GFM "Disallowed Raw HTML" (tagfilter); only meaningful with `unsafe_html`.
     */
    public var gfmTagfilter: Bool
    /**
     * GFM footnotes (`[^1]` + `[^1]:` → footnote section).
     */
    public var gfmFootnotes: Bool
    /**
     * Math: `$…$` / `\(…\)` inline and `$$…$$` / `\[…\]` display.
     */
    public var gfmMath: Bool
    /**
     * Emit `dir="auto"` on block-level text elements (mixed LTR/RTL).
     */
    public var dirAuto: Bool
    /**
     * Opt-in accessibility markup (task-list `<label>`, header `scope="col"`).
     */
    public var a11y: Bool
    /**
     * Pass raw HTML through unescaped. **Never enable for untrusted input.**
     */
    public var unsafeHtml: Bool
    /**
     * Block component-tag allowlist (e.g. `["Thinking", "Callout"]`). `None` = off.
     */
    public var componentTags: [String]?
    /**
     * Inline component-tag allowlist (e.g. `["tik", "cite"]`). `None` = off.
     */
    public var inlineComponentTags: [String]?
    /**
     * Safe raw-HTML allowlist. `Some([])` = allow all but a built-in dangerous
     * set; `Some([tags])` = only those; `None` = sanitizer off. Setting this (or
     * `drop_html_tags`) engages the sanitizer.
     */
    public var htmlAllowlist: [String]?
    /**
     * Tags removed entirely by the sanitizer. Setting this (or `html_allowlist`)
     * engages the sanitizer. `None` = off.
     */
    public var dropHtmlTags: [String]?
    /**
     * Opt-in structured `kind.data` channel (Heading/CodeBlock/Table/… payloads).
     */
    public var blockData: Bool
    /**
     * Opt-in wire delta mode (WIRE.md §11): active blocks re-emitted across
     * appends serialize as verified `html_delta` splices against their
     * previous emit instead of full `html`. A consumer that enables this MUST
     * reconstruct active html per WIRE.md §11 (the brookmd-react-native JS
     * layer does). Off by default — wire bytes identical to contract v1.1.0.
     */
    public var wireDelta: Bool
    /**
     * Render a CommonMark SOFT line break (a bare `\n` in inline content) as a
     * `<br>` — the "GitHub comment" convention. Off by default (strict CommonMark:
     * a soft break is whitespace). Only ever ADDS breaks; hard breaks are `<br>`
     * either way.
     */
    public var softBreaks: Bool
    /**
     * Un-block URL schemes that are blocked by DEFAULT — bare scheme names
     * without the colon (`["file"]`), matched case-insensitively. `None` = the
     * built-in policy is unchanged. This never RESTRICTS anything, and the
     * script-executing tier (`javascript:`, `data:text/html`, …) is
     * non-overridable — listing one here is a no-op.
     */
    public var allowSchemes: [String]?
    /**
     * Lenient list indentation: a list marker followed by 6+ columns of SPACE
     * padding yields the item's text instead of an indented code block. Off by
     * default (strict CommonMark §5.2); useful for over-indenting model output.
     */
    public var lenientLists: Bool
    /**
     * Extend the safe raw-HTML sanitizer to BLOCK-level raw HTML (a
     * `<details><summary>…` block renders as real elements). Takes effect ONLY
     * when the sanitizer is engaged (`html_allowlist`/`drop_html_tags`), and only
     * for CommonMark HTML block types 6 and 7. Off by default.
     */
    public var blockHtml: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * GFM extended autolinks (bare `www.`/`http(s)://`/`ftp://` + emails).
         */gfmAutolinks: Bool = true, 
        /**
         * GitHub alerts (`> [!NOTE]` → styled callouts).
         */gfmAlerts: Bool = true, 
        /**
         * GFM "Disallowed Raw HTML" (tagfilter); only meaningful with `unsafe_html`.
         */gfmTagfilter: Bool = false, 
        /**
         * GFM footnotes (`[^1]` + `[^1]:` → footnote section).
         */gfmFootnotes: Bool = false, 
        /**
         * Math: `$…$` / `\(…\)` inline and `$$…$$` / `\[…\]` display.
         */gfmMath: Bool = false, 
        /**
         * Emit `dir="auto"` on block-level text elements (mixed LTR/RTL).
         */dirAuto: Bool = false, 
        /**
         * Opt-in accessibility markup (task-list `<label>`, header `scope="col"`).
         */a11y: Bool = false, 
        /**
         * Pass raw HTML through unescaped. **Never enable for untrusted input.**
         */unsafeHtml: Bool = false, 
        /**
         * Block component-tag allowlist (e.g. `["Thinking", "Callout"]`). `None` = off.
         */componentTags: [String]? = nil, 
        /**
         * Inline component-tag allowlist (e.g. `["tik", "cite"]`). `None` = off.
         */inlineComponentTags: [String]? = nil, 
        /**
         * Safe raw-HTML allowlist. `Some([])` = allow all but a built-in dangerous
         * set; `Some([tags])` = only those; `None` = sanitizer off. Setting this (or
         * `drop_html_tags`) engages the sanitizer.
         */htmlAllowlist: [String]? = nil, 
        /**
         * Tags removed entirely by the sanitizer. Setting this (or `html_allowlist`)
         * engages the sanitizer. `None` = off.
         */dropHtmlTags: [String]? = nil, 
        /**
         * Opt-in structured `kind.data` channel (Heading/CodeBlock/Table/… payloads).
         */blockData: Bool = false, 
        /**
         * Opt-in wire delta mode (WIRE.md §11): active blocks re-emitted across
         * appends serialize as verified `html_delta` splices against their
         * previous emit instead of full `html`. A consumer that enables this MUST
         * reconstruct active html per WIRE.md §11 (the brookmd-react-native JS
         * layer does). Off by default — wire bytes identical to contract v1.1.0.
         */wireDelta: Bool = false, 
        /**
         * Render a CommonMark SOFT line break (a bare `\n` in inline content) as a
         * `<br>` — the "GitHub comment" convention. Off by default (strict CommonMark:
         * a soft break is whitespace). Only ever ADDS breaks; hard breaks are `<br>`
         * either way.
         */softBreaks: Bool = false, 
        /**
         * Un-block URL schemes that are blocked by DEFAULT — bare scheme names
         * without the colon (`["file"]`), matched case-insensitively. `None` = the
         * built-in policy is unchanged. This never RESTRICTS anything, and the
         * script-executing tier (`javascript:`, `data:text/html`, …) is
         * non-overridable — listing one here is a no-op.
         */allowSchemes: [String]? = nil, 
        /**
         * Lenient list indentation: a list marker followed by 6+ columns of SPACE
         * padding yields the item's text instead of an indented code block. Off by
         * default (strict CommonMark §5.2); useful for over-indenting model output.
         */lenientLists: Bool = false, 
        /**
         * Extend the safe raw-HTML sanitizer to BLOCK-level raw HTML (a
         * `<details><summary>…` block renders as real elements). Takes effect ONLY
         * when the sanitizer is engaged (`html_allowlist`/`drop_html_tags`), and only
         * for CommonMark HTML block types 6 and 7. Off by default.
         */blockHtml: Bool = false) {
        self.gfmAutolinks = gfmAutolinks
        self.gfmAlerts = gfmAlerts
        self.gfmTagfilter = gfmTagfilter
        self.gfmFootnotes = gfmFootnotes
        self.gfmMath = gfmMath
        self.dirAuto = dirAuto
        self.a11y = a11y
        self.unsafeHtml = unsafeHtml
        self.componentTags = componentTags
        self.inlineComponentTags = inlineComponentTags
        self.htmlAllowlist = htmlAllowlist
        self.dropHtmlTags = dropHtmlTags
        self.blockData = blockData
        self.wireDelta = wireDelta
        self.softBreaks = softBreaks
        self.allowSchemes = allowSchemes
        self.lenientLists = lenientLists
        self.blockHtml = blockHtml
    }

    

    
}

#if compiler(>=6)
extension BrookConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBrookConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BrookConfig {
        return
            try BrookConfig(
                gfmAutolinks: FfiConverterBool.read(from: &buf), 
                gfmAlerts: FfiConverterBool.read(from: &buf), 
                gfmTagfilter: FfiConverterBool.read(from: &buf), 
                gfmFootnotes: FfiConverterBool.read(from: &buf), 
                gfmMath: FfiConverterBool.read(from: &buf), 
                dirAuto: FfiConverterBool.read(from: &buf), 
                a11y: FfiConverterBool.read(from: &buf), 
                unsafeHtml: FfiConverterBool.read(from: &buf), 
                componentTags: FfiConverterOptionSequenceString.read(from: &buf), 
                inlineComponentTags: FfiConverterOptionSequenceString.read(from: &buf), 
                htmlAllowlist: FfiConverterOptionSequenceString.read(from: &buf), 
                dropHtmlTags: FfiConverterOptionSequenceString.read(from: &buf), 
                blockData: FfiConverterBool.read(from: &buf), 
                wireDelta: FfiConverterBool.read(from: &buf), 
                softBreaks: FfiConverterBool.read(from: &buf), 
                allowSchemes: FfiConverterOptionSequenceString.read(from: &buf), 
                lenientLists: FfiConverterBool.read(from: &buf), 
                blockHtml: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: BrookConfig, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.gfmAutolinks, into: &buf)
        FfiConverterBool.write(value.gfmAlerts, into: &buf)
        FfiConverterBool.write(value.gfmTagfilter, into: &buf)
        FfiConverterBool.write(value.gfmFootnotes, into: &buf)
        FfiConverterBool.write(value.gfmMath, into: &buf)
        FfiConverterBool.write(value.dirAuto, into: &buf)
        FfiConverterBool.write(value.a11y, into: &buf)
        FfiConverterBool.write(value.unsafeHtml, into: &buf)
        FfiConverterOptionSequenceString.write(value.componentTags, into: &buf)
        FfiConverterOptionSequenceString.write(value.inlineComponentTags, into: &buf)
        FfiConverterOptionSequenceString.write(value.htmlAllowlist, into: &buf)
        FfiConverterOptionSequenceString.write(value.dropHtmlTags, into: &buf)
        FfiConverterBool.write(value.blockData, into: &buf)
        FfiConverterBool.write(value.wireDelta, into: &buf)
        FfiConverterBool.write(value.softBreaks, into: &buf)
        FfiConverterOptionSequenceString.write(value.allowSchemes, into: &buf)
        FfiConverterBool.write(value.lenientLists, into: &buf)
        FfiConverterBool.write(value.blockHtml, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrookConfig_lift(_ buf: RustBuffer) throws -> BrookConfig {
    return try FfiConverterTypeBrookConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBrookConfig_lower(_ value: BrookConfig) -> RustBuffer {
    return FfiConverterTypeBrookConfig.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_brook_md_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_brook_md_ffi_checksum_method_brooksession_all_blocks() != 46557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brook_md_ffi_checksum_method_brooksession_append() != 15626) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brook_md_ffi_checksum_method_brooksession_buffer_len() != 7914) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brook_md_ffi_checksum_method_brooksession_finalize() != 60540) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brook_md_ffi_checksum_method_brooksession_reset() != 39920) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brook_md_ffi_checksum_method_brooksession_retained_bytes() != 8193) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brook_md_ffi_checksum_constructor_brooksession_new() != 2220) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_brook_md_ffi_checksum_constructor_brooksession_new_with_config() != 3151) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBrookMdFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all